[app]
platformio_cmd = platformio
cubemx_cmd = /home/thanasis/STM32CubeMX/STM32CubeMX
java_cmd = None

[project]
cubemx_script_content = config load ${ioc_file_absolute_path}
	generate code ${project_dir_absolute_path}
	exit
platformio_ini_patch_content = [platformio]
	include_dir = Inc
	src_dir = Src
board = nucleo_h743zi
ioc_file = Buck_VoltageMode_HW_pio.ioc
cleanup_ignore = Buck_VoltageMode_HW_pio.ioc
cleanup_use_git = False
inspect_ioc = True
last_error = FileNotFoundError: [Errno 2] No such file or directory: '/home/efthym/STM32CubeMX/STM32CubeMX': '/home/efthym/STM32CubeMX/STM32CubeMX'
	Traceback (most recent call last):
	  File "/home/thanasis/.local/lib/python3.7/site-packages/stm32pio/cli/app.py", line 198, in main
	    project.generate_code()
	  File "/home/thanasis/.local/lib/python3.7/site-packages/stm32pio/core/project.py", line 129, in generate_code
	    return self.cubemx.generate_code(script_template=self.config.get('project', 'cubemx_script_content'))
	  File "/home/thanasis/.local/lib/python3.7/site-packages/stm32pio/core/cubemx.py", line 201, in generate_code
	    completed_process, std_output = self.execute_script(cubemx_script_content)
	  File "/home/thanasis/.local/lib/python3.7/site-packages/stm32pio/core/cubemx.py", line 180, in execute_script
	    raise e  # re-raise an exception after the 'finally' block
	  File "/home/thanasis/.local/lib/python3.7/site-packages/stm32pio/core/cubemx.py", line 176, in execute_script
	    completed_process = subprocess.run(command_arr, stdout=log.pipe, stderr=log.pipe)
	  File "/usr/lib/python3.7/subprocess.py", line 472, in run
	    with Popen(*popenargs, **kwargs) as process:
	  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
	    restore_signals, start_new_session)
	  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
	    raise child_exception_type(errno_num, err_msg, err_filename)

